name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  #

jobs:
  mock-deploy:
    name: Simulate Docker build and smoke test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Simulate Docker build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: my-app:ci-test
      - name: Run container for smoke test
        run: |
          docker run -d --name test-app -p 8080:8080 my-app:ci-test
          sleep 10
          docker ps
